import type { Exporter, ExportContext, ExportedFile } from "./types.js";
import type { RequestVariant } from "../variants/index.js";
import { resolvePath, queryString, bodyText, groupByEndpoint, slug, usedVariables } from "./util.js";

function block(v: RequestVariant): string {
  const lines: string[] = [];
  lines.push(`### ${v.name}  (expects ${v.expectedStatus})`);
  lines.push(`${v.method} {{baseUrl}}${resolvePath(v.routeTemplate, v.pathParams)}${queryString(v.query)}`);

  const hasContentType = v.headers.some((h) => h.name.toLowerCase() === "content-type");
  for (const h of v.headers) lines.push(`${h.name}: ${h.value}`);

  const body = bodyText(v);
  if (body !== undefined) {
    if (!hasContentType) lines.push(`Content-Type: ${v.body!.contentType}`);
    lines.push("");
    lines.push(body);
  }
  return lines.join("\n");
}

export const httpExporter: Exporter = {
  id: "http",
  label: ".http (REST Client)",
  export(ctx: ExportContext): ExportedFile[] {
    const blocks: string[] = [`# ${ctx.ir.service.name} — generated by reqweave`, ""];
    for (const g of groupByEndpoint(ctx.variants)) {
      for (const v of g.variants) blocks.push(block(v));
    }
    const httpFile = `${blocks.join("\n\n")}\n`;

    const env: Record<string, Record<string, string>> = { dev: {} };
    for (const k of usedVariables(ctx.variants)) {
      env.dev![k] = k === "baseUrl" ? ctx.options.baseUrl : "";
    }

    const base = slug(ctx.ir.service.name);
    return [
      { path: `http/${base}.http`, content: httpFile },
      { path: "http/http-client.env.json", content: `${JSON.stringify(env, null, 2)}\n` },
    ];
  },
};
