import type { Exporter, ExportContext, ExportedFile } from "./types.js";
import type { RequestVariant } from "../variants/index.js";
import {
  resolvePath,
  rewritePlaceholders,
  bodyText,
  deterministicId,
  groupByEndpoint,
  stableStringify,
  slug,
  usedVariables,
} from "./util.js";

const tx = (s: string) => rewritePlaceholders(s, "insomnia");

export const insomniaExporter: Exporter = {
  id: "insomnia",
  label: "Insomnia v4",
  export(ctx: ExportContext): ExportedFile[] {
    const wrk = `wrk_${deterministicId(`${ctx.ir.service.name}:insomnia`).replace(/-/g, "")}`;
    const resources: unknown[] = [
      { _id: wrk, _type: "workspace", name: ctx.ir.service.name, description: "Generated by reqweave", scope: "collection" },
    ];

    const envData: Record<string, string> = {};
    for (const k of usedVariables(ctx.variants)) envData[k] = k === "baseUrl" ? ctx.options.baseUrl : "";
    resources.push({
      _id: `env_${deterministicId(`${ctx.ir.service.name}:insomnia-env`).replace(/-/g, "")}`,
      _type: "environment",
      parentId: wrk,
      name: "Base Environment",
      data: envData,
    });

    let sort = -1;
    for (const g of groupByEndpoint(ctx.variants)) {
      const fld = `fld_${deterministicId(`${ctx.ir.service.name}:${g.endpointId}`).replace(/-/g, "")}`;
      resources.push({ _id: fld, _type: "request_group", parentId: wrk, name: g.endpointId });
      for (const v of g.variants) {
        resources.push(requestResource(v, fld, sort--));
      }
    }

    const doc = { _type: "export", __export_format: 4, __export_source: "reqweave", resources };
    return [{ path: `insomnia/${slug(ctx.ir.service.name)}.insomnia.json`, content: `${stableStringify(doc)}\n` }];
  },
};

function requestResource(v: RequestVariant, parentId: string, sortKey: number): unknown {
  const body = bodyText(v);
  return {
    _id: `req_${deterministicId(`${v.endpointId}:${v.name}`).replace(/-/g, "")}`,
    _type: "request",
    parentId,
    name: v.name,
    method: v.method,
    url: tx(`{{baseUrl}}${resolvePath(v.routeTemplate, v.pathParams)}`),
    parameters: v.query.map((q) => ({ name: q.name, value: tx(q.value) })),
    headers: v.headers.map((h) => ({ name: h.name, value: tx(h.value) })),
    body: body === undefined ? {} : { mimeType: v.body!.contentType, text: tx(body) },
    metaSortKey: sortKey,
  };
}
